### PR TITLE
fix: make sure hidden section not appearing in sidebar

### LINKED ISSUE #905: Hidden section still appears in sidebar
**Description**

When hiding a section in configuration, links to the section and its children remains in the sidebar.

**Steps to reproduce**

Paste the following into the [playground](https://asyncapi.github.io/asyncapi-react/):

<details><summary>Schema</summary>

```json
{
  "asyncapi": "3.0.0",
  "info": {
    "title": "Reproduction",
    "version": "1.0.0"
  },
  "operations": {
    "test": {
      "action": "receive",
      "channel": { "$ref": "#/channels/test" }
    }
  },
  "channels": {
    "test": {
      "address": "/test",
      "messages": {
        "test": { "$ref": "#/components/messages/test" }
      }
    }
  },
  "components": {
    "messages": {
      "test": {
        "payload": {
          "type": "object",
          "properties": {
            "test": {
              "description": "test",
              "type": "string",
              "pattern": "^(?:helloworld)+$"
            }
          },
          "required": ["test"]
        }
      }
    }
  }
}
```

</details>

<details><summary>Configuration</summary>

```json
{
  "show": {
    "sidebar": true,
    "info": true,
    "operations": true,
    "servers": true,
    "messages": false,
    "schemas": true,
    "errors": true
  },
  "expand":{
    "messageExamples": false
  },
  "sidebar": {
    "showServers": "byDefault",
    "showOperations": "byDefault"
  }
}
```

</details>

**Expected result**

Section "messages" to be removed from the page and from the sidebar.

**Actual result**

Section "messages" is removed from the page, but not from the sidebar.

**Troubleshooting**

N/A

### PR DESCRIPTION
**Pull request by AceTheCreator**
This PR fixes the issue of hidden sections still appearing in the sidebar

fixes #905

### CODE REVIEW

File: library/src/containers/Sidebar/Sidebar.tsx [hunk 1]
```diff
@@ -75,6 +79,7 @@ export const Sidebar: React.FunctionComponent = () => {
 
   const operationList = hasOperations && (
     <>
+      <h1>Testing</h1>
```
Comment (derberg) [inline library/src/containers/Sidebar/Sidebar.tsx:82]: I don't think it should stay in the code

Comment (AceTheCreator) [reply library/src/containers/Sidebar/Sidebar.tsx:82]: Oh! 🫣

**Review by derberg — APPROVED** [review]
